# html_templates.py

def get_base_html():
    """Возвращает базовую структуру HTML"""
    return """<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Trivy SploitScan Report</title>

  <!-- Tailwind (CDN runtime) -->
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {{
      darkMode: 'class',
      theme: {{
        extend: {{
          colors: {{
            brand: {{
              50: '#eef2ff',
              100: '#e0e7ff',
              500: '#6366f1',
              600: '#4f46e5',
              700: '#4338ca'
            }},
            kev: '#16a34a',
            prioAPlus: '#ef4444',
            prioA: '#f97316',
            prioB: '#f59e0b',
            prioC: '#3b82f6',
            prioD: '#10b981'
          }}
        }}
      }}
    }}
  </script>

  <style>
    {css_styles}
  </style>
</head>
<body id="top" class="bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-gray-100 transition-colors">
  <!-- Header -->
  <header class="border-b border-gray-200 bg-white/70 backdrop-blur-md dark:border-gray-800 dark:bg-gray-900/70 sticky top-0 z-30 shadow-sm">
    <div class="mx-auto container-fixed px-4">
      <div class="flex items-center justify-between py-3">
        <div class="flex items-center gap-3">
          <div class="h-8 w-8 rounded bg-brand-600"></div>
          <div>
            <h1 class="text-lg font-semibold tracking-tight">Trivy SploitScan Report</h1>
            <p class="text-xs muted">Enhanced vulnerability assessment with exploit intelligence</p>
          </div>
        </div>
        <div class="flex items-center gap-2 no-print">
          <button id="themeToggle" class="inline-flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <svg id="sun" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 hidden dark:block" viewBox="0 0 24 24" fill="currentColor"><path d="M6.76 4.84l-1.8-1.79L3.17 4.84l1.79 1.79 1.8-1.79zM1 13h3v-2H1v2zm10-9h2V1h-2v3zm7.03 1.21l1.79-1.79-1.79-1.79-1.79 1.79 1.79 1.79zM20 11v2h3v-2h-3zm-9 10h2v-3h-2v3zm-7.03-2.21l1.8 1.79 1.79-1.79-1.79-1.79-1.8 1.79zM18.36 17.2l1.79 1.79 1.79-1.79-1.79-1.79-1.79 1.79zM12 6a6 6 0 100 12A6 6 0 0012 6z"/></svg>
            <svg id="moon" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 block dark:hidden" viewBox="0 0 24 24" fill="currentColor"><path d="M20.742 13.045a8.088 8.088 0 01-9.787-9.787A9.004 9.004 0 0012 21a9.004 9.004 0 008.742-7.955z"/></svg>
            <span class="hidden sm:inline">Theme</span>
          </button>
          <button onclick="window.print()" class="inline-flex items-center gap-2 rounded-md border border-gray-300 bg-white px-3 py-1.5 text-sm font-medium hover:bg-gray-50 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 24 24" fill="currentColor"><path d="M6 9V2h12v7h2a2 2 0 012 2v4h-4v6H6v-6H2v-4a2 2 0 012-2h2zm2-5v5h8V4H8zm8 10H8v4h8v-4z"/></svg>
            <span class="hidden sm:inline">Print</span>
          </button>
        </div>
      </div>
    </div>
  </header>

  <main class="mx-auto container-fixed px-4 py-6">
    {main_content}
  </main>

  <footer class="mx-auto container-fixed px-4 py-8 text-center muted text-xs">
    Generated by Trivy SploitScan • {total_cves} CVE(s) • {timestamp}
  </footer>

  <script>
    {javascript}
  </script>
</body>
</html>"""


def get_css_styles():
    """Возвращает CSS стили"""
    return """
    /* IMPORTANT: No Tailwind @apply here since we use CDN runtime. Define plain CSS so layout looks correct without a build step. */

    :root { font-feature-settings: "rlig" 1, "calt" 1; }
    body, button, input, select, textarea {
      font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans",
                   "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
    }
    .container-fixed { max-width: 1200px; }

    .badge {
      display: inline-flex;
      align-items: center;
      border-radius: 9999px;
      padding: 2px 8px;
      font-size: 12px;
      font-weight: 500;
      line-height: 1.2;
    }

    .card {
      border-radius: 12px;
      border: 1px solid #e5e7eb;
      background: #ffffff;
      box-shadow: 0 1px 2px rgba(0,0,0,0.04);
    }
    .dark .card {
      border-color: #374151;
      background: #1f2937;
    }

    .card-header {
      border-bottom: 1px solid #e5e7eb;
      padding: 16px 24px;
    }
    .dark .card-header {
      border-color: #374151;
    }

    .card-body { padding: 24px; }

    .muted { color: #6b7280; }
    .dark .muted { color: #9ca3af; }

    .link {
      color: #4f46e5;
      text-decoration: underline;
      text-underline-offset: 2px;
    }
    .link:hover { color: #4338ca; }

    .pill {
      padding: 2px 8px;
      border-radius: 6px;
      font-size: 12px;
      font-weight: 600;
      line-height: 1.2;
    }

    .tooltip { position: relative; }
    .tooltip:hover:after {
      content: attr(data-tip);
      position: absolute;
      bottom: 125%;
      left: 50%;
      transform: translateX(-50%);
      background-color: rgba(17, 24, 39, 0.95);
      color: white;
      padding: 6px 8px;
      border-radius: 6px;
      font-size: 12px;
      white-space: nowrap;
      z-index: 20;
    }

    .table-row { border-bottom: 1px solid #f3f4f6; }
    .dark .table-row { border-color: #374151; }

    .sticky-sidebar { position: sticky; top: 1rem; height: calc(100vh - 2rem); }
    .scroll-area { max-height: calc(100vh - 12rem); }

    .chip {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      border-radius: 9999px;
      background: #f3f4f6;
      padding: 4px 8px;
      font-size: 12px;
      font-weight: 500;
      color: #374151;
    }
    .dark .chip {
      background: #374151;
      color: #e5e7eb;
    }

    /* Priority color pills */
    .priority-A+ { background: #fee2e2; color: #991b1b; }
    .priority-A { background: #ffedd5; color: #9a3412; }
    .priority-B { background: #fef3c7; color: #92400e; }
    .priority-C { background: #dbeafe; color: #1e40af; }
    .priority-D { background: #dcfce7; color: #065f46; }

    @media print {
      .no-print { display: none !important; }
      .card { box-shadow: none !important; }
      .sticky, .sticky-sidebar { position: static !important; height: auto !important; }
      a[href]:after { content: " (" attr(href) ") "; font-size: 0.85em; color: #6b7280; }
      html { background: #fff; }
      body { color: #111827 !important; }
    }

    /* UI polish */
    #summaryTable thead {
      position: sticky;
      top: 0;
      background: #ffffff;
      z-index: 2;
      box-shadow: 0 1px 0 rgba(0,0,0,0.06);
    }
    .dark #summaryTable thead {
      background: #0b1220;
      box-shadow: 0 1px 0 rgba(255,255,255,0.08);
    }

    /* Ensure anchor jumps land with spacing below the sticky header */
    article.card { scroll-margin-top: 96px; }

    /* Heading and spacing polish */
    .card-header h2, .card-header h3 { letter-spacing: 0.2px; }
    h3 { line-height: 1.3; }

    /* Wrap long URLs in lists for better readability */
    ul { word-break: break-word; }
    li > a { word-break: break-all; }

    /* Hide scrollbar for sidebar COMPLETELY - no hover effect */
    .scrollbar-hide {
      -ms-overflow-style: none;  /* IE and Edge */
      scrollbar-width: none;     /* Firefox */
    }
    .scrollbar-hide::-webkit-scrollbar {
      display: none;  /* Chrome, Safari and Opera */
      width: 0;
      height: 0;
    }

    /* ДЛЯ ДЛИННЫХ НАЗВАНИЙ СЕКЦИЙ - ПЕРЕНОС СЛОВ */
    .break-words {
        word-break: break-word;
        overflow-wrap: break-word;
        hyphens: auto;
    }

    /* Убедимся, что текст занимает доступное пространство */
    .min-w-0 {
        min-width: 0;
    }

    .flex-shrink-0 {
        flex-shrink: 0;
    }

    /* Анимация для стрелочки */
    .rotate-180 {
        transform: rotate(180deg);
    }

    /* Для плавной анимации раскрытия */
    .section-content {
        transition: max-height 0.3s ease;
        overflow: hidden;
    }

    /* Улучшение отображения длинных имен пакетов */
    .section-content a {
        display: block;
        max-width: 100%;
        word-break: break-word;
    }

    /* Выравнивание по вертикали */
    .align-middle {
        vertical-align: middle;
    }

    /* Для кнопок с иконками */
    .section-toggle {
        flex-shrink: 0;
    }

    /* Для правильного переноса длинных названий секций */
    .section-title {
        display: block;
        overflow-wrap: anywhere;
    }

    /* Улучшенные отступы для дерева навигации */
    .tree-item {
        margin-bottom: 0.25rem;
    }

    /* Подсветка активной секции */
    :target {
        animation: highlight 2s ease;
    }

    @keyframes highlight {
        0% { background-color: rgba(99, 102, 241, 0.1); }
        100% { background-color: transparent; }
    }

    /* Отступ для якорных ссылок на пакеты */
    div[id] {
        scroll-margin-top: 100px;
    }

    /* ИСПРАВЛЕННЫЙ ВАРИАНТ - ВОЗВРАЩАЕМ РАННИЙ СТИЛЬ СКРОЛЛБАРА */
    .sticky-sidebar { 
        position: sticky; 
        top: 1rem;
        max-height: calc(100vh - 2rem);
        overflow-y: auto;
        /* СКРЫВАЕМ СКРОЛЛБАР У SIDEBAR */
        scrollbar-width: none; /* Firefox */
        -ms-overflow-style: none; /* IE/Edge */
    }

    /* Скрываем скроллбар у sidebar в Chrome/Safari */
    .sticky-sidebar::-webkit-scrollbar {
        display: none;
        width: 0;
        height: 0;
    }

    .sections-container {
        display: block;
    }

    .tree-content {
        display: block;
        max-height: none;
    }

    /* Ограничение высоты для раскрытых секций с ОРИГИНАЛЬНЫМ ТОНКИМ СКРОЛЛБАРОМ */
    .section-content {
        max-height: 0;
        overflow: hidden;
        transition: max-height 0.3s ease;
    }

    .section-content:not(.hidden) {
        max-height: 250px;
        overflow-y: auto;
        margin-bottom: 8px;
    }

    /* ОРИГИНАЛЬНЫЙ ТОНКИЙ СКРОЛЛБАР ДЛЯ ВЫПАДАЮЩИХ МЕНЮ (как было изначально) */
    .section-content:not(.hidden)::-webkit-scrollbar {
        width: 4px;
    }

    .section-content:not(.hidden)::-webkit-scrollbar-track {
        background: #f3f4f6;
        border-radius: 2px;
    }

    .section-content:not(.hidden)::-webkit-scrollbar-thumb {
        background: #d1d5db;
        border-radius: 2px;
    }

    .dark .section-content:not(.hidden)::-webkit-scrollbar-track {
        background: #374151;
    }

    .dark .section-content:not(.hidden)::-webkit-scrollbar-thumb {
        background: #4b5563;
    }
    """


def get_javascript():
    """Возвращает JavaScript код"""
    return """
    // Theme toggle
    (function() {
      const root = document.documentElement;
      const toggle = document.getElementById('themeToggle');
      function setTheme(dark) {
        if (dark) {
          root.classList.add('dark');
        } else {
          root.classList.remove('dark');
        }
        localStorage.setItem('theme', dark ? 'dark' : 'light');
      }
      const saved = localStorage.getItem('theme');
      setTheme(saved ? saved === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches);
      if (toggle) {
        toggle.addEventListener('click', function() {
          setTheme(!root.classList.contains('dark'));
        });
      }
    })();

    // Filters: search, priority, severity, epss, cisa, exploits, status
    document.addEventListener('DOMContentLoaded', function() {
      const input = document.getElementById('searchInput');
      const epssInput = document.getElementById('filterEPSS');
      const cisaCheckbox = document.getElementById('filterCISA');
      const exploitCheckbox = document.getElementById('filterExploit');
      const resetBtn = document.getElementById('resetFilters');
      const visibleCounter = document.getElementById('visibleCounter');
      const visibleCount = document.getElementById('visibleCount');
      const totalCount = document.getElementById('totalCount');

      if (!input) return;

      const vulnerabilityCards = document.querySelectorAll('.vulnerability-card');
      let selectedPrios = new Set();
      let selectedSeverities = new Set();
      let selectedStatuses = new Set();

      // Update counter function
      function updateVisibleCounter(visibleCards) {
        visibleCount.textContent = visibleCards;
        totalCount.textContent = vulnerabilityCards.length;

        // Show/hide counter based on whether any filters are active
        const hasActiveFilters = 
          input.value.trim() !== '' ||
          (epssInput && epssInput.value !== '') ||
          (cisaCheckbox && cisaCheckbox.checked) ||
          (exploitCheckbox && exploitCheckbox.checked) ||
          selectedPrios.size > 0 ||
          selectedSeverities.size > 0 ||
          selectedStatuses.size > 0;

        if (hasActiveFilters) {
          visibleCounter.classList.remove('hidden');
        } else {
          visibleCounter.classList.add('hidden');
        }
      }

      // Initialize priority filters
      document.querySelectorAll('.prio').forEach(function(btn) {
        btn.addEventListener('click', function() {
          const p = this.getAttribute('data-prio');
          if (selectedPrios.has(p)) {
            selectedPrios.delete(p);
            this.classList.remove('ring-2', 'ring-brand-600');
          } else {
            selectedPrios.add(p);
            this.classList.add('ring-2', 'ring-brand-600');
          }
          applyFilters();
        });
      });

      // Initialize severity filters
      document.querySelectorAll('.severity').forEach(function(btn) {
        btn.addEventListener('click', function() {
          const s = this.getAttribute('data-severity');
          if (selectedSeverities.has(s)) {
            selectedSeverities.delete(s);
            this.classList.remove('ring-2', 'ring-brand-600');
          } else {
            selectedSeverities.add(s);
            this.classList.add('ring-2', 'ring-brand-600');
          }
          applyFilters();
        });
      });

      // Initialize status filters
      document.querySelectorAll('.status').forEach(function(btn) {
        btn.addEventListener('click', function() {
          const s = this.getAttribute('data-status');
          if (selectedStatuses.has(s)) {
            selectedStatuses.delete(s);
            this.classList.remove('ring-2', 'ring-brand-600');
          } else {
            selectedStatuses.add(s);
            this.classList.add('ring-2', 'ring-brand-600');
          }
          applyFilters();
        });
      });

      // Event listeners for other filters
      input.addEventListener('input', applyFilters);

      if (epssInput) epssInput.addEventListener('input', applyFilters);
      if (cisaCheckbox) cisaCheckbox.addEventListener('change', applyFilters);
      if (exploitCheckbox) exploitCheckbox.addEventListener('change', applyFilters);

      // Reset filters
      if (resetBtn) {
        resetBtn.addEventListener('click', function() {
          input.value = '';
          if (epssInput) epssInput.value = '';
          if (cisaCheckbox) cisaCheckbox.checked = false;
          if (exploitCheckbox) exploitCheckbox.checked = false;

          selectedPrios.clear();
          document.querySelectorAll('.prio').forEach(function(btn) {
            btn.classList.remove('ring-2', 'ring-brand-600');
          });

          selectedSeverities.clear();
          document.querySelectorAll('.severity').forEach(function(btn) {
            btn.classList.remove('ring-2', 'ring-brand-600');
          });

          selectedStatuses.clear();
          document.querySelectorAll('.status').forEach(function(btn) {
            btn.classList.remove('ring-2', 'ring-brand-600');
          });

          applyFilters();
        });
      }

      function applyFilters() {
        const q = input.value.toLowerCase().trim();
        const epssMin = epssInput ? parseFloat(epssInput.value) / 100 || 0 : 0;
        const showCISA = cisaCheckbox && cisaCheckbox.checked;
        const showExploits = exploitCheckbox && exploitCheckbox.checked;

        let visibleCards = 0;

        // Apply filters to all cards
        vulnerabilityCards.forEach(function(card) {
          const cardCve = card.getAttribute('data-cve') || '';
          const cardPackage = card.getAttribute('data-package') || '';
          const cardPr = card.getAttribute('data-prio') || '';
          const cardSeverity = card.getAttribute('data-severity') || '';
          const cardEpss = parseFloat(card.getAttribute('data-epss')) || 0;
          const cardCisa = card.getAttribute('data-cisa') === 'true';
          const cardExpl = card.getAttribute('data-expl') === 'true';
          const cardStatus = card.getAttribute('data-status') || '';

          let visible = true;

          // Search by CVE ID OR Package name
          if (q && !cardCve.toLowerCase().includes(q) && !cardPackage.toLowerCase().includes(q)) {
            visible = false;
          }

          // Priority filter
          if (visible && selectedPrios.size > 0 && !selectedPrios.has(cardPr)) {
            visible = false;
          }

          // Severity filter
          if (visible && selectedSeverities.size > 0 && !selectedSeverities.has(cardSeverity)) {
            visible = false;
          }

          // Status filter
          if (visible && selectedStatuses.size > 0 && !selectedStatuses.has(cardStatus)) {
            visible = false;
          }

          // EPSS filter
          if (visible && cardEpss < epssMin) {
            visible = false;
          }

          // CISA KEV filter
          if (visible && showCISA && !cardCisa) {
            visible = false;
          }

          // Exploit filter
          if (visible && showExploits && !cardExpl) {
            visible = false;
          }

          if (visible) {
            card.style.display = '';
            visibleCards++;
          } else {
            card.style.display = 'none';
          }
        });

        // Update package and section visibility
        updatePackageAndSectionVisibility();

        // Update visible counter
        updateVisibleCounter(visibleCards);
      }

      function updatePackageAndSectionVisibility() {
        // Process all sections
        document.querySelectorAll('article.card').forEach(function(section) {
          let sectionHasVisibleContent = false;

          // Process all packages in section
          section.querySelectorAll('div.mb-6').forEach(function(packageDiv) {
            const packageCards = packageDiv.querySelectorAll('.vulnerability-card');
            const visiblePackageCards = Array.from(packageCards).filter(function(card) {
              return card.style.display !== 'none';
            });

            // Show package if it has visible cards, otherwise hide
            if (visiblePackageCards.length > 0) {
              packageDiv.style.display = '';
              sectionHasVisibleContent = true;
            } else {
              packageDiv.style.display = 'none';
            }
          });

          // Show section if it has visible content, otherwise hide
          section.style.display = sectionHasVisibleContent ? '' : 'none';
        });
      }

      // Initialize on load
      applyFilters();
    });

    // Tree navigation toggle and smooth scroll
    document.addEventListener('DOMContentLoaded', function() {
      // Функция для переключения секции
      function toggleSection(sectionId, button) {
        const content = document.getElementById(`section-${sectionId}`);
        const icon = button.querySelector('svg');

        if (content.classList.contains('hidden')) {
          content.classList.remove('hidden');
          icon.classList.add('rotate-180');
        } else {
          content.classList.add('hidden');
          icon.classList.remove('rotate-180');
        }
      }

      // Обработчики для кнопок раскрытия/скрытия (только для иконок)
      document.querySelectorAll('.section-toggle').forEach(function(button) {
        button.addEventListener('click', function(e) {
          e.preventDefault();
          e.stopPropagation(); // Останавливаем всплытие
          const sectionId = this.getAttribute('data-section');
          toggleSection(sectionId, this);
        });
      });

      // Отключаем раскрытие при клике на ссылку секции
      document.querySelectorAll('.section-link').forEach(function(link) {
        link.addEventListener('click', function(e) {
          // Если это ссылка на секцию, останавливаем всплытие
          e.stopPropagation();
        });
      });

      // Обработчик кликов на ссылках в боковой панели для плавной прокрутки
      document.querySelectorAll('a[href^="#"]').forEach(function(anchor) {
        anchor.addEventListener('click', function(e) {
          const href = this.getAttribute('href');
          if (href === '#') return;

          const targetId = href.substring(1);
          const targetElement = document.getElementById(targetId);

          if (targetElement) {
            e.preventDefault();

            // Раскрываем родительскую секцию, если она скрыта и это ссылка на пакет
            if (targetId.includes('__')) {
              const sectionId = targetId.split('__')[0];
              const sectionToggle = document.querySelector(`.section-toggle[data-section="${sectionId}"]`);
              const sectionContent = document.getElementById(`section-${sectionId}`);

              if (sectionToggle && sectionContent && sectionContent.classList.contains('hidden')) {
                toggleSection(sectionId, sectionToggle);
              }
            }

            // Плавная прокрутка
            const headerOffset = 96; // Отступ для фиксированного хедера
            const elementPosition = targetElement.getBoundingClientRect().top;
            const offsetPosition = elementPosition + window.pageYOffset - headerOffset;

            window.scrollTo({
              top: offsetPosition,
              behavior: 'smooth'
            });
          }
        });
      });

      // Auto-expand section if URL has hash on page load
      if (window.location.hash) {
        const targetId = window.location.hash.substring(1);

        // Если это ссылка на пакет, раскрываем его секцию
        if (targetId.includes('__')) {
          const sectionId = targetId.split('__')[0];
          const sectionToggle = document.querySelector(`.section-toggle[data-section="${sectionId}"]`);
          const sectionContent = document.getElementById(`section-${sectionId}`);

          if (sectionToggle && sectionContent && sectionContent.classList.contains('hidden')) {
            // Даем время на загрузку DOM
            setTimeout(function() {
              toggleSection(sectionId, sectionToggle);
            }, 100);
          }
        }
      }

      // Вызываем при загрузке и при изменении размера окна
      setTimeout(updateSectionsHeight, 100); // Даем время на рендеринг
      window.addEventListener('resize', updateSectionsHeight);

      // Также обновляем при раскрытии/закрытии секций
      document.querySelectorAll('.section-toggle').forEach(function(button) {
        button.addEventListener('click', function() {
          setTimeout(updateSectionsHeight, 350); // После анимации
        });
      });
    });
    """